pdftoppm -jpeg ../swar/a_anar/a_anar.pdf ../swar/a_anar/a_anar
pdftoppm -jpeg ../swar/aa_aam/aa_aam.pdf ../swar/aa_aam/aa_aam
pdftoppm -jpeg ../swar/e-emli/e_emli.pdf ../swar/e-emli/e_emli
pdftoppm -jpeg ../swar/i_inkh/i_inkh.pdf ../swar/i_inkh/i_inkh
pdftoppm -jpeg ../swar/u_ullu/u_ullu.pdf ../swar/u_ullu/u_ullu
pdftoppm -jpeg ../swar/o_oon/o_oon.pdf ../swar/o_oon/o_oon
pdftoppm -jpeg ../swar/rh_Rishi/rh_rishi.pdf ../swar/rh_Rishi/rh_rishi
pdftoppm -jpeg ../swar/ae_aedi/ae_aedi.pdf ../swar/ae_aedi/ae_aedi
pdftoppm -jpeg ../swar/aai_ainak/aai_ainak.pdf ../swar/aai_ainak/aai_ainak
pdftoppm -jpeg ../swar/o_ookhli/o_ookhli.pdf ../swar/o_ookhli/o_ookhli
pdftoppm -jpeg ../swar/au_aurat/au_aurat.pdf ../swar/au_aurat/au_aurat
pdftoppm -jpeg ../swar/am_angutha/am_angutha.pdf ../swar/am_angutha/am_angutha
pdftoppm -jpeg ../swar/aha/aha.pdf ../swar/aha/aha
